"""added field name on CityHall

Revision ID: 0b9ae0b79eaf
Revises: b0a75b5273c0
Create Date: 2023-06-08 15:52:33.880915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9ae0b79eaf'
down_revision = 'b0a75b5273c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)

    with op.batch_alter_table('prefeitura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(), nullable=False))
        batch_op.alter_column('secretario',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_endereco',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('prefeitura', schema=None) as batch_op:
        batch_op.alter_column('id_endereco',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('secretario',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('nome')

    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
