"""ajuste em viagem no id_fundionario p o id_motorista, e ajustado id veiculo em viagem

Revision ID: 59eeb8e63045
Revises: f23b2501b29b
Create Date: 2023-07-03 00:05:09.049188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59eeb8e63045'
down_revision = 'f23b2501b29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)

    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)

    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_motorista', sa.Integer(), nullable=True))
        batch_op.alter_column('id_veiculo',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('viagem_id_funcionario_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'motorista', ['id_motorista'], ['id_funcionario'])
        batch_op.create_foreign_key(None, 'veiculo', ['id_veiculo'], ['id'])
        batch_op.drop_column('id_funcionario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_funcionario', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('viagem_id_funcionario_fkey', 'motorista', ['id_funcionario'], ['id_funcionario'])
        batch_op.alter_column('id_veiculo',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id_motorista')

    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
