"""ajuste em viagem:id_motorista passou para id_funcionario

Revision ID: 5b0f8792b9bf
Revises: 59eeb8e63045
Create Date: 2023-07-03 00:23:42.501407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0f8792b9bf'
down_revision = '59eeb8e63045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)

    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)

    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_funcionario', sa.Integer(), nullable=True))
        batch_op.drop_constraint('viagem_id_motorista_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'motorista', ['id_funcionario'], ['id_funcionario'])
        batch_op.drop_column('id_motorista')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_motorista', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('viagem_id_motorista_fkey', 'motorista', ['id_motorista'], ['id_funcionario'])
        batch_op.drop_column('id_funcionario')

    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
