"""criado tabela de pretensao

Revision ID: 62bfe968421d
Revises: 392cbce2246f
Create Date: 2023-07-01 23:26:50.177404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62bfe968421d'
down_revision = '392cbce2246f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rota', sa.Integer(), nullable=True),
    sa.Column('id_motorista', sa.Integer(), nullable=True),
    sa.Column('id_veiculo', sa.Integer(), nullable=True),
    sa.Column('data_viagem', sa.DateTime(), nullable=False),
    sa.Column('criacao', sa.DateTime(), nullable=False),
    sa.Column('turno', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_motorista'], ['motorista.id_funcionario'], ),
    sa.ForeignKeyConstraint(['id_rota'], ['rota.id'], ),
    sa.ForeignKeyConstraint(['id_veiculo'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pretensao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_viagem', sa.Integer(), nullable=True),
    sa.Column('id_aluno', sa.Integer(), nullable=True),
    sa.Column('embarque', sa.Boolean(), nullable=False),
    sa.Column('data_embarque', sa.DateTime(), nullable=False),
    sa.Column('criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id_pessoa'], ),
    sa.ForeignKeyConstraint(['id_viagem'], ['viagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)

    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)

    op.drop_table('pretensao')
    op.drop_table('viagem')
    # ### end Alembic commands ###
