"""ajuste em viagem - movido p id_funcionario

Revision ID: 933271af311b
Revises: 5eb2b83e5da7
Create Date: 2023-07-02 20:27:15.334843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933271af311b'
down_revision = '5eb2b83e5da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)

    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)

    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_funcionario', sa.Integer(), nullable=True))
        batch_op.drop_constraint('viagem_id_veiculo_fkey', type_='foreignkey')
        batch_op.drop_constraint('viagem_id_motorista_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'motorista', ['id_funcionario'], ['id_funcionario'])
        batch_op.drop_column('id_veiculo')
        batch_op.drop_column('id_motorista')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_motorista', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_veiculo', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('viagem_id_motorista_fkey', 'motorista', ['id_motorista'], ['id_funcionario'])
        batch_op.create_foreign_key('viagem_id_veiculo_fkey', 'veiculo', ['id_veiculo'], ['id'])
        batch_op.drop_column('id_funcionario')

    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
