"""adjusted variables types

Revision ID: acc5f06bf81f
Revises: 
Create Date: 2023-06-06 13:57:37.872174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc5f06bf81f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('uf',
    sa.Column('codigo_uf', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(precision=8), nullable=False),
    sa.Column('longitude', sa.Float(precision=8), nullable=False),
    sa.Column('regiao', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('codigo_uf')
    )
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('qtd_passageiros', sa.Integer(), nullable=False),
    sa.Column('tipo_veiculo', sa.String(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cidade',
    sa.Column('codigo_ibge', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(precision=8), nullable=False),
    sa.Column('longitude', sa.Float(precision=8), nullable=False),
    sa.Column('capital', sa.Boolean(), nullable=False),
    sa.Column('codigo_uf', sa.Integer(), nullable=False),
    sa.Column('siafi_id', sa.String(length=4), nullable=False),
    sa.Column('ddd', sa.Integer(), nullable=False),
    sa.Column('fuso_horario', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_uf'], ['uf.codigo_uf'], ),
    sa.PrimaryKeyConstraint('codigo_ibge')
    )
    op.create_table('funcionario',
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id_pessoa')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('id_cidade', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=False),
    sa.Column('referencia', sa.String(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_cidade'], ['cidade.codigo_ibge'], ),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motorista',
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('id_veiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionario.id_pessoa'], ),
    sa.ForeignKeyConstraint(['id_veiculo'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id_funcionario')
    )
    op.create_table('instituicao_ensino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('id_endereco', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_endereco'], ['endereco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prefeitura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secretario', sa.Integer(), nullable=True),
    sa.Column('id_endereco', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_endereco'], ['endereco.id'], ),
    sa.ForeignKeyConstraint(['secretario'], ['funcionario.id_pessoa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno',
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(), nullable=True),
    sa.Column('curso', sa.String(), nullable=True),
    sa.Column('turno', sa.String(), nullable=True),
    sa.Column('id_instituicao_ensino', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_instituicao_ensino'], ['instituicao_ensino.id'], ),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id_pessoa'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('rota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_motorista', sa.Integer(), nullable=True),
    sa.Column('id_veiculo', sa.Integer(), nullable=True),
    sa.Column('id_instituicao_ensino', sa.Integer(), nullable=True),
    sa.Column('id_prefeitura', sa.Integer(), nullable=True),
    sa.Column('cidade_origem', sa.String(), nullable=False),
    sa.Column('cidade_destino', sa.String(), nullable=False),
    sa.Column('qdt_alunos', sa.Integer(), nullable=False),
    sa.Column('horario_saida', sa.DateTime(), nullable=False),
    sa.Column('horario_chegada', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_instituicao_ensino'], ['instituicao_ensino.id'], ),
    sa.ForeignKeyConstraint(['id_motorista'], ['motorista.id_funcionario'], ),
    sa.ForeignKeyConstraint(['id_prefeitura'], ['prefeitura.id'], ),
    sa.ForeignKeyConstraint(['id_veiculo'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passageiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=True),
    sa.Column('cidade_origem', sa.String(), nullable=False),
    sa.Column('cidade_destino', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id_pessoa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passageiro')
    op.drop_table('rota')
    op.drop_table('aluno')
    op.drop_table('prefeitura')
    op.drop_table('instituicao_ensino')
    op.drop_table('motorista')
    op.drop_table('endereco')
    op.drop_table('funcionario')
    op.drop_table('cidade')
    op.drop_table('veiculo')
    op.drop_table('uf')
    op.drop_table('pessoa')
    # ### end Alembic commands ###
