"""criado rota_instituicao

Revision ID: cab188b640a1
Revises: 133f4cc2f756
Create Date: 2023-07-03 14:44:41.334160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab188b640a1'
down_revision = '133f4cc2f756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rota_instituicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rota', sa.Integer(), nullable=True),
    sa.Column('id_instituicao_ensino', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_instituicao_ensino'], ['instituicao_ensino.id'], ),
    sa.ForeignKeyConstraint(['id_rota'], ['rota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)

    with op.batch_alter_table('rota', schema=None) as batch_op:
        batch_op.drop_constraint('rota_id_motorista_fkey', type_='foreignkey')
        batch_op.drop_constraint('rota_id_instituicao_ensino_fkey', type_='foreignkey')
        batch_op.drop_column('id_instituicao_ensino')
        batch_op.drop_column('id_motorista')

    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('rota', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_motorista', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_instituicao_ensino', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('rota_id_instituicao_ensino_fkey', 'instituicao_ensino', ['id_instituicao_ensino'], ['id'])
        batch_op.create_foreign_key('rota_id_motorista_fkey', 'motorista', ['id_motorista'], ['id_funcionario'])

    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)

    op.drop_table('rota_instituicao')
    # ### end Alembic commands ###
