"""adicionado id_veiculo em model de viagem

Revision ID: f23b2501b29b
Revises: 933271af311b
Create Date: 2023-07-02 21:01:15.324755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23b2501b29b'
down_revision = '933271af311b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)

    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)

    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_veiculo', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.drop_column('id_veiculo')

    with op.batch_alter_table('uf', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('cidade', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
